require "luaext"
require "util"
require "globaldef"
require "errno"
require "enum"

teammatchdefine = require"teammatchdefine"
weapondefine = require"weapondefine"
warehousedefine = require"warehousedefine"
buffdefine = require"buffdefine"
battledefine = require"battledefine"
businessdefine = require"businessdefine"
blueprintdefine = require"blueprintdefine"
chipdefine = require"chipdefine"
addictiondefine = require"addictiondefine"
achievementdefine = require"achievementdefine"
assignmentdefine = require"assignmentdefine"