--[[

 @file:       jackpot.lua
 @source xls: excel_3D\Store.xlsx
 @sheet name: JACKPOT
 @brief:      this file was create by tools, DO NOT modify it!
 @author:     kevin

]]--
        local JACKPOT = {
	[1] = {Jackpot_Name= "金币拍卖出售概率", Jackpot_Discribe= "第一次价格刷新;第二次价格刷新...;未卖出", Jackpot_1= {500, 20, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, }, Jackpot_2 = {}, },
	[2] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[3] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[4] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[5] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[6] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[7] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[8] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[9] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[10] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[11] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[12] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[13] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[14] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[15] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[16] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[17] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[18] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[19] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[20] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[21] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[22] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[23] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[24] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[25] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[26] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[27] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[28] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[29] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[30] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[31] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[32] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[33] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[34] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[35] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[36] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[37] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[38] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[39] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[40] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[41] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[42] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[43] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[44] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[45] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[46] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[47] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[48] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[49] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[50] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[51] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[52] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[53] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[54] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[55] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[56] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[57] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[58] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[59] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[60] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[61] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[62] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[63] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[64] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[65] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[66] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[67] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
	[68] = {Jackpot_Name= "", Jackpot_Discribe= "", Jackpot_1 = {}, Jackpot_2 = {}, },
};return JACKPOT