--[[

 @file:       skill.lua
 @source xls: excel_3D\Skill.xlsx
 @sheet name: SKILL
 @brief:      this file was create by tools, DO NOT modify it!
 @author:     kevin

]]--
        local SKILL = {
	[10001] = {Buff_ID= {20002, 0, }, Skill_Name= "信标传送", Image1= "Texture2D'/Game/Texture/UI/Battle/skill/athena_battle_UI_skill_tp_01.athena_battle_UI_skill_tp_01'", Skill_Type=3, If_Skip=0, Power_Consume=50, Weapon_ID=10030, Skill_CD=0.0, Skill_Duration=0.0, Skill_Strength=0.0, Effict_During=3, Skill_SpecialEffict1= "ParticleSystem'/Game/Particles/Weapon/Aura/Athena_battle_aura_10001_01.Athena_battle_aura_10001_01'", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "ParticleSystem'/Game/Particles/Weapon/Sheld/Athena_battle_speacialeffects_body_birth_10001_1.Athena_battle_speacialeffects_body_birth_10001_1'", Skill_SpecialEffict4= "ParticleSystem'/Game/Particles/Weapon/Sheld/Athena_battle_speacialeffects_body_birth_10001_2.Athena_battle_speacialeffects_body_birth_10001_2'", Skill_Voice= "", Use_Voice= "", },
	[10002] = {Buff_ID= {20003, 0, }, Skill_Name= "弹跳", Image1= "Texture2D'/Game/Texture/UI/Battle/skill/athena_battle_UI_skill_jump_01.athena_battle_UI_skill_jump_01'", Skill_Type=2, If_Skip=0, Power_Consume=15, Weapon_ID=0, Skill_CD=0.0, Skill_Duration=0.0, Skill_Strength=0.0, Effict_During=3, Skill_SpecialEffict1= "ParticleSystem'/Game/Particles/Weapon/Aura/Athena_battle_aura_10002_01.Athena_battle_aura_10002_01'", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "ParticleSystem'/Game/Particles/Weapon/Fire/Athena_battle_speacialeffects_weapon_fire_10001_1.Athena_battle_speacialeffects_weapon_fire_10001_1'", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10003] = {Buff_ID= {20004, 0, }, Skill_Name= "连射", Image1= "Texture2D'/Game/Texture/UI/Battle/skill/athena_battle_UI_skill_Burst_01.athena_battle_UI_skill_Burst_01'", Skill_Type=2, If_Skip=1, Power_Consume=50, Weapon_ID=0, Skill_CD=0.0, Skill_Duration=0.0, Skill_Strength=0.0, Effict_During=3, Skill_SpecialEffict1= "ParticleSystem'/Game/Particles/Weapon/Aura/Athena_battle_aura_10003_01.Athena_battle_aura_10003_01'", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10004] = {Buff_ID= {20005, 0, }, Skill_Name= "散射", Image1= "Texture2D'/Game/Texture/UI/Battle/skill/athena_battle_UI_skill_scattering_01.athena_battle_UI_skill_scattering_01'", Skill_Type=2, If_Skip=1, Power_Consume=50, Weapon_ID=0, Skill_CD=0.0, Skill_Duration=0.0, Skill_Strength=0.0, Effict_During=3, Skill_SpecialEffict1= "ParticleSystem'/Game/Particles/Weapon/Aura/Athena_battle_aura_10004_01.Athena_battle_aura_10004_01'", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10005] = {Buff_ID= {20005, 0, }, Skill_Name= "子母弹", Image1= "Image1", Skill_Type=0, If_Skip=0, Power_Consume=0, Weapon_ID=0, Skill_CD=0.0, Skill_Duration=0.0, Skill_Strength=0.0, Effict_During=0, Skill_SpecialEffict1= "", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10006] = {Buff_ID= {20006, 0, }, Skill_Name= "冲刺", Image1= "Image1", Skill_Type=2, If_Skip=1, Power_Consume=0, Weapon_ID=0, Skill_CD=0.0, Skill_Duration=0.0, Skill_Strength=0.0, Effict_During=1, Skill_SpecialEffict1= "", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10007] = {Buff_ID= {10007, 0, }, Skill_Name= "", Image1= "", Skill_Type=0, If_Skip=0, Power_Consume=0, Weapon_ID=0, Skill_CD=0, Skill_Duration=0, Skill_Strength=0, Effict_During=0, Skill_SpecialEffict1= "", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10008] = {Buff_ID= {10008, 0, }, Skill_Name= "", Image1= "", Skill_Type=0, If_Skip=0, Power_Consume=0, Weapon_ID=0, Skill_CD=0, Skill_Duration=0, Skill_Strength=0, Effict_During=0, Skill_SpecialEffict1= "", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10009] = {Buff_ID= {10009, 0, }, Skill_Name= "", Image1= "", Skill_Type=0, If_Skip=0, Power_Consume=0, Weapon_ID=0, Skill_CD=0, Skill_Duration=0, Skill_Strength=0, Effict_During=0, Skill_SpecialEffict1= "", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10010] = {Buff_ID= {10010, 0, }, Skill_Name= "", Image1= "", Skill_Type=0, If_Skip=0, Power_Consume=0, Weapon_ID=0, Skill_CD=0, Skill_Duration=0, Skill_Strength=0, Effict_During=0, Skill_SpecialEffict1= "", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
	[10011] = {Buff_ID= {10011, 0, }, Skill_Name= "", Image1= "", Skill_Type=0, If_Skip=0, Power_Consume=0, Weapon_ID=0, Skill_CD=0, Skill_Duration=0, Skill_Strength=0, Effict_During=0, Skill_SpecialEffict1= "", Skill_SpecialEffict2= "", Skill_SpecialEffict3= "", Skill_SpecialEffict4= "", Skill_Voice= "", Use_Voice= "", },
};return SKILL