--[[

 @file:       achievement.lua
 @source xls: excel_3D\Achievement.xlsx
 @sheet name: ACHIEVEMENT
 @brief:      this file was create by tools, DO NOT modify it!
 @author:     kevin

]]--
        local ACHIEVEMENT = {
	[1] = {Achievement_Name= "通关1-1", Achievement_Discribe= "通关1-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10001, }, If_Get=1, },
	[2] = {Achievement_Name= "通关1-2", Achievement_Discribe= "通关1-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10002, }, If_Get=1, },
	[3] = {Achievement_Name= "通关1-3", Achievement_Discribe= "通关1-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10003, }, If_Get=1, },
	[4] = {Achievement_Name= "通关1-4", Achievement_Discribe= "通关1-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10004, }, If_Get=1, },
	[5] = {Achievement_Name= "通关1-5", Achievement_Discribe= "通关1-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10005, }, If_Get=1, },
	[6] = {Achievement_Name= "通关1-6", Achievement_Discribe= "通关1-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10006, }, If_Get=1, },
	[7] = {Achievement_Name= "通关1-7", Achievement_Discribe= "通关1-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10007, }, If_Get=1, },
	[8] = {Achievement_Name= "通关2-1", Achievement_Discribe= "通关2-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10008, }, If_Get=1, },
	[9] = {Achievement_Name= "通关2-2", Achievement_Discribe= "通关2-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10009, }, If_Get=1, },
	[10] = {Achievement_Name= "通关2-3", Achievement_Discribe= "通关2-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10010, }, If_Get=1, },
	[11] = {Achievement_Name= "通关2-4", Achievement_Discribe= "通关2-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10011, }, If_Get=1, },
	[12] = {Achievement_Name= "通关2-5", Achievement_Discribe= "通关2-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10012, }, If_Get=1, },
	[13] = {Achievement_Name= "通关2-6", Achievement_Discribe= "通关2-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10013, }, If_Get=1, },
	[14] = {Achievement_Name= "通关2-7", Achievement_Discribe= "通关2-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10014, }, If_Get=1, },
	[15] = {Achievement_Name= "通关3-1", Achievement_Discribe= "通关3-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10015, }, If_Get=1, },
	[16] = {Achievement_Name= "通关3-2", Achievement_Discribe= "通关3-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10016, }, If_Get=1, },
	[17] = {Achievement_Name= "通关3-3", Achievement_Discribe= "通关3-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10017, }, If_Get=1, },
	[18] = {Achievement_Name= "通关3-4", Achievement_Discribe= "通关3-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10018, }, If_Get=1, },
	[19] = {Achievement_Name= "通关3-5", Achievement_Discribe= "通关3-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10019, }, If_Get=1, },
	[20] = {Achievement_Name= "通关3-6", Achievement_Discribe= "通关3-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10020, }, If_Get=1, },
	[21] = {Achievement_Name= "通关3-7", Achievement_Discribe= "通关3-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10021, }, If_Get=1, },
	[22] = {Achievement_Name= "通关4-1", Achievement_Discribe= "通关4-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10022, }, If_Get=1, },
	[23] = {Achievement_Name= "通关4-2", Achievement_Discribe= "通关4-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10023, }, If_Get=1, },
	[24] = {Achievement_Name= "通关4-3", Achievement_Discribe= "通关4-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10024, }, If_Get=1, },
	[25] = {Achievement_Name= "通关4-4", Achievement_Discribe= "通关4-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10025, }, If_Get=1, },
	[26] = {Achievement_Name= "通关4-5", Achievement_Discribe= "通关4-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10026, }, If_Get=1, },
	[27] = {Achievement_Name= "通关4-6", Achievement_Discribe= "通关4-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10027, }, If_Get=1, },
	[28] = {Achievement_Name= "通关4-7", Achievement_Discribe= "通关4-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10028, }, If_Get=1, },
	[29] = {Achievement_Name= "通关5-1", Achievement_Discribe= "通关5-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10029, }, If_Get=1, },
	[30] = {Achievement_Name= "通关5-2", Achievement_Discribe= "通关5-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10030, }, If_Get=1, },
	[31] = {Achievement_Name= "通关5-3", Achievement_Discribe= "通关5-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10031, }, If_Get=1, },
	[32] = {Achievement_Name= "通关5-4", Achievement_Discribe= "通关5-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10032, }, If_Get=1, },
	[33] = {Achievement_Name= "通关5-5", Achievement_Discribe= "通关5-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10033, }, If_Get=1, },
	[34] = {Achievement_Name= "通关5-6", Achievement_Discribe= "通关5-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10034, }, If_Get=1, },
	[35] = {Achievement_Name= "通关5-7", Achievement_Discribe= "通关5-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10035, }, If_Get=1, },
	[36] = {Achievement_Name= "通关6-1", Achievement_Discribe= "通关6-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10036, }, If_Get=1, },
	[37] = {Achievement_Name= "通关6-2", Achievement_Discribe= "通关6-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10037, }, If_Get=1, },
	[38] = {Achievement_Name= "通关6-3", Achievement_Discribe= "通关6-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10038, }, If_Get=1, },
	[39] = {Achievement_Name= "通关6-4", Achievement_Discribe= "通关6-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10039, }, If_Get=1, },
	[40] = {Achievement_Name= "通关6-5", Achievement_Discribe= "通关6-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10040, }, If_Get=1, },
	[41] = {Achievement_Name= "通关6-6", Achievement_Discribe= "通关6-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10041, }, If_Get=1, },
	[42] = {Achievement_Name= "通关6-7", Achievement_Discribe= "通关6-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10042, }, If_Get=1, },
	[43] = {Achievement_Name= "通关7-1", Achievement_Discribe= "通关7-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10043, }, If_Get=1, },
	[44] = {Achievement_Name= "通关7-2", Achievement_Discribe= "通关7-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10044, }, If_Get=1, },
	[45] = {Achievement_Name= "通关7-3", Achievement_Discribe= "通关7-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10045, }, If_Get=1, },
	[46] = {Achievement_Name= "通关7-4", Achievement_Discribe= "通关7-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10046, }, If_Get=1, },
	[47] = {Achievement_Name= "通关7-5", Achievement_Discribe= "通关7-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10047, }, If_Get=1, },
	[48] = {Achievement_Name= "通关7-6", Achievement_Discribe= "通关7-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10048, }, If_Get=1, },
	[49] = {Achievement_Name= "通关7-7", Achievement_Discribe= "通关7-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10049, }, If_Get=1, },
	[50] = {Achievement_Name= "通关8-1", Achievement_Discribe= "通关8-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10050, }, If_Get=1, },
	[51] = {Achievement_Name= "通关8-2", Achievement_Discribe= "通关8-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10051, }, If_Get=1, },
	[52] = {Achievement_Name= "通关8-3", Achievement_Discribe= "通关8-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10052, }, If_Get=1, },
	[53] = {Achievement_Name= "通关8-4", Achievement_Discribe= "通关8-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10053, }, If_Get=1, },
	[54] = {Achievement_Name= "通关8-5", Achievement_Discribe= "通关8-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10054, }, If_Get=1, },
	[55] = {Achievement_Name= "通关8-6", Achievement_Discribe= "通关8-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10055, }, If_Get=1, },
	[56] = {Achievement_Name= "通关8-7", Achievement_Discribe= "通关8-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10056, }, If_Get=1, },
	[57] = {Achievement_Name= "通关9-1", Achievement_Discribe= "通关9-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10057, }, If_Get=1, },
	[58] = {Achievement_Name= "通关9-2", Achievement_Discribe= "通关9-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10058, }, If_Get=1, },
	[59] = {Achievement_Name= "通关9-3", Achievement_Discribe= "通关9-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10059, }, If_Get=1, },
	[60] = {Achievement_Name= "通关9-4", Achievement_Discribe= "通关9-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10060, }, If_Get=1, },
	[61] = {Achievement_Name= "通关9-5", Achievement_Discribe= "通关9-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10061, }, If_Get=1, },
	[62] = {Achievement_Name= "通关9-6", Achievement_Discribe= "通关9-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10062, }, If_Get=1, },
	[63] = {Achievement_Name= "通关9-7", Achievement_Discribe= "通关9-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10063, }, If_Get=1, },
	[64] = {Achievement_Name= "通关10-1", Achievement_Discribe= "通关10-1", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10064, }, If_Get=1, },
	[65] = {Achievement_Name= "通关10-2", Achievement_Discribe= "通关10-2", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10065, }, If_Get=1, },
	[66] = {Achievement_Name= "通关10-3", Achievement_Discribe= "通关10-3", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10066, }, If_Get=1, },
	[67] = {Achievement_Name= "通关10-4", Achievement_Discribe= "通关10-4", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10067, }, If_Get=1, },
	[68] = {Achievement_Name= "通关10-5", Achievement_Discribe= "通关10-5", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10068, }, If_Get=1, },
	[69] = {Achievement_Name= "通关10-6", Achievement_Discribe= "通关10-6", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10069, }, If_Get=1, },
	[70] = {Achievement_Name= "通关10-7", Achievement_Discribe= "通关10-7", Achievement_Item=1, Achievement_Page=1, Achievement_Object= {10070, }, If_Get=1, },
	[71] = {Achievement_Name= "进行1次完整战斗的次数", Achievement_Discribe= "进行1次完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {1, }, If_Get=1, },
	[72] = {Achievement_Name= "进行10次完整战斗的次数", Achievement_Discribe= "进行10次完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {10, }, If_Get=1, },
	[73] = {Achievement_Name= "进行50次完整战斗的次数", Achievement_Discribe= "进行50次完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {50, }, If_Get=1, },
	[74] = {Achievement_Name= "进行100完整战斗的次数", Achievement_Discribe= "进行100完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {100, }, If_Get=1, },
	[75] = {Achievement_Name= "进行200次完整战斗的次数", Achievement_Discribe= "进行200次完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {200, }, If_Get=1, },
	[76] = {Achievement_Name= "进行500次完整战斗的次数", Achievement_Discribe= "进行500次完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {500, }, If_Get=1, },
	[77] = {Achievement_Name= "进行1000次完整战斗的次数", Achievement_Discribe= "进行1000次完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {1000, }, If_Get=1, },
	[78] = {Achievement_Name= "进行2000完整战斗的次数", Achievement_Discribe= "进行2000完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {2000, }, If_Get=1, },
	[79] = {Achievement_Name= "进行5000次完整战斗的次数", Achievement_Discribe= "进行5000次完整战斗的次数", Achievement_Item=1001, Achievement_Page=2, Achievement_Object= {5000, }, If_Get=0, },
	[80] = {Achievement_Name= "", Achievement_Discribe= "", Achievement_Item=1001, Achievement_Page=2, Achievement_Object = {}, If_Get=0, },
	[81] = {Achievement_Name= "", Achievement_Discribe= "", Achievement_Item=1002, Achievement_Page=3, Achievement_Object = {}, If_Get=0, },
};return ACHIEVEMENT