--[[

 @file:       task_object.lua
 @source xls: excel_3D\Achievement.xlsx
 @sheet name: TASK_OBJECT
 @brief:      this file was create by tools, DO NOT modify it!
 @author:     kevin

]]--
        local TASK_OBJECT = {
	[1] = {Task_Discribe= "击杀特定敌人", Achevement_ID=1010, Contain_ID = {}, Task_Count=1, If_Bigger=1, Parameter= "1.0", Task_Fuction=1, },
	[2] = {Task_Discribe= "敌人死亡", Achevement_ID=1036, Contain_ID= {90001, }, Task_Count=1, If_Bigger=1, Parameter= "2.0", Task_Fuction=2, },
	[3] = {Task_Discribe= "", Achevement_ID=10003, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[4] = {Task_Discribe= "", Achevement_ID=10004, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[5] = {Task_Discribe= "", Achevement_ID=10005, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[6] = {Task_Discribe= "", Achevement_ID=10006, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[7] = {Task_Discribe= "", Achevement_ID=10007, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[8] = {Task_Discribe= "", Achevement_ID=10008, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[9] = {Task_Discribe= "", Achevement_ID=10009, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[10] = {Task_Discribe= "", Achevement_ID=10010, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[11] = {Task_Discribe= "", Achevement_ID=10011, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[12] = {Task_Discribe= "", Achevement_ID=10012, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[13] = {Task_Discribe= "", Achevement_ID=10013, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[14] = {Task_Discribe= "", Achevement_ID=10014, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[15] = {Task_Discribe= "", Achevement_ID=10015, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[16] = {Task_Discribe= "", Achevement_ID=10016, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[17] = {Task_Discribe= "", Achevement_ID=10017, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[18] = {Task_Discribe= "", Achevement_ID=10018, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[19] = {Task_Discribe= "", Achevement_ID=10019, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[20] = {Task_Discribe= "", Achevement_ID=10020, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[21] = {Task_Discribe= "", Achevement_ID=10021, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[22] = {Task_Discribe= "", Achevement_ID=10022, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[23] = {Task_Discribe= "", Achevement_ID=10023, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[24] = {Task_Discribe= "", Achevement_ID=10024, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[25] = {Task_Discribe= "", Achevement_ID=10025, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[26] = {Task_Discribe= "", Achevement_ID=10026, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[27] = {Task_Discribe= "", Achevement_ID=10027, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[28] = {Task_Discribe= "", Achevement_ID=10028, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[29] = {Task_Discribe= "", Achevement_ID=10029, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[30] = {Task_Discribe= "", Achevement_ID=10030, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[31] = {Task_Discribe= "", Achevement_ID=10031, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[32] = {Task_Discribe= "", Achevement_ID=10032, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[33] = {Task_Discribe= "", Achevement_ID=10033, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[34] = {Task_Discribe= "", Achevement_ID=10034, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[35] = {Task_Discribe= "", Achevement_ID=10035, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[36] = {Task_Discribe= "", Achevement_ID=10036, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[37] = {Task_Discribe= "", Achevement_ID=10037, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[38] = {Task_Discribe= "", Achevement_ID=10038, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[39] = {Task_Discribe= "", Achevement_ID=10039, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[40] = {Task_Discribe= "", Achevement_ID=10040, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[41] = {Task_Discribe= "", Achevement_ID=10041, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[42] = {Task_Discribe= "", Achevement_ID=10042, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[43] = {Task_Discribe= "", Achevement_ID=10043, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[44] = {Task_Discribe= "", Achevement_ID=10044, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[45] = {Task_Discribe= "", Achevement_ID=10045, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[46] = {Task_Discribe= "", Achevement_ID=10046, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[47] = {Task_Discribe= "", Achevement_ID=10047, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[48] = {Task_Discribe= "", Achevement_ID=10048, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[49] = {Task_Discribe= "", Achevement_ID=10049, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[50] = {Task_Discribe= "", Achevement_ID=10050, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[51] = {Task_Discribe= "", Achevement_ID=10051, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[52] = {Task_Discribe= "", Achevement_ID=10052, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[53] = {Task_Discribe= "", Achevement_ID=10053, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[54] = {Task_Discribe= "", Achevement_ID=10054, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[55] = {Task_Discribe= "", Achevement_ID=10055, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[56] = {Task_Discribe= "", Achevement_ID=10056, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[57] = {Task_Discribe= "", Achevement_ID=10057, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[58] = {Task_Discribe= "", Achevement_ID=10058, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[59] = {Task_Discribe= "", Achevement_ID=10059, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[60] = {Task_Discribe= "", Achevement_ID=10060, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[61] = {Task_Discribe= "", Achevement_ID=10061, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[62] = {Task_Discribe= "", Achevement_ID=10062, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[63] = {Task_Discribe= "", Achevement_ID=10063, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[64] = {Task_Discribe= "", Achevement_ID=10064, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[65] = {Task_Discribe= "", Achevement_ID=10065, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[66] = {Task_Discribe= "", Achevement_ID=10066, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[67] = {Task_Discribe= "", Achevement_ID=10067, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[68] = {Task_Discribe= "", Achevement_ID=10068, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[69] = {Task_Discribe= "", Achevement_ID=10069, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[70] = {Task_Discribe= "", Achevement_ID=10070, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[71] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=1, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[72] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=10, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[73] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=50, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[74] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=100, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[75] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=200, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[76] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=500, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[77] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=1000, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[78] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=2000, If_Bigger=0, Parameter= "", Task_Fuction=0, },
	[79] = {Task_Discribe= "", Achevement_ID=1, Contain_ID = {}, Task_Count=5000, If_Bigger=0, Parameter= "", Task_Fuction=0, },
};return TASK_OBJECT