--[[

 @file:       ai.lua
 @source xls: excel_3D\AI.xlsx
 @sheet name: AI
 @brief:      this file was create by tools, DO NOT modify it!
 @author:     kevin

]]--
        local AI = {
	[10001] = {AI_Name= "伏地魔", K1=1, K2=0, Blueprint= "BehaviorTree'/Game/Blueprints/Battle/NPC/AI/BT_EnemyRemote.BT_EnemyRemote'", Weapon_modelID=90001, Weapon_Type=10008, Damage_Type=10001, Damage_Rad=500, Break_Rad=500, Break_Strength=0, Base_Damage=12, InitialSpeedMax=10000, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=90010, Hp=500, Hp_Restore=0.0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0.5, Body_Damage=0.8, Sheld_Restore=0, Power_Value=200, Power_Restore=100, FireConcrol_modelID=90010, Attack_Angle_Max=30, Attack_Angle_Min=80, Angular_Acceleration=0.2, Power_Efficiency=0.7, Speed_X=700, Round_Speed=0, Chassis_Creeping_Angle=60, Chassis_Creeping_Hight=85, Chassis_Correction=10, Attach= "0.0", engine_efficiency=0.015, },
	[10002] = {AI_Name= "近战莽夫", K1=1, K2=0, Blueprint= "BehaviorTree'/Game/Blueprints/Battle/NPC/AI/BT_EnemyCloseCombat.BT_EnemyCloseCombat'", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=90010, Hp=500, Hp_Restore=5.0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0.5, Body_Damage=0.8, Sheld_Restore=0, Power_Value=300, Power_Restore=200, FireConcrol_modelID=90010, Attack_Angle_Max=60, Attack_Angle_Min=30, Angular_Acceleration=0.2, Power_Efficiency=0.7, Speed_X=700, Round_Speed=0, Chassis_Creeping_Angle=60, Chassis_Creeping_Hight=85, Chassis_Correction=10, Attach= "0.0", engine_efficiency=0.015, },
	[10003] = {AI_Name= "傻逼", K1=0, K2=0, Blueprint= "BehaviorTree'/Game/Blueprints/Battle/NPC/AI/BT_Idiot.BT_Idiot'", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=90010, Hp=470, Hp_Restore=0.0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0.5, Body_Damage=0.8, Sheld_Restore=0, Power_Value=200, Power_Restore=100, FireConcrol_modelID=90010, Attack_Angle_Max=40, Attack_Angle_Min=50, Angular_Acceleration=0.2, Power_Efficiency=0.6, Speed_X=700, Round_Speed=0, Chassis_Creeping_Angle=60, Chassis_Creeping_Hight=85, Chassis_Correction=10, Attach= "0.0", engine_efficiency=0.015, },
	[10004] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=90010, Hp=300, Hp_Restore=0.0, Sheld_Type=1, Sheld_Value=200, Shield_Damage_Reduce=0.5, Body_Damage=1.0, Sheld_Restore=15, Power_Value=50, Power_Restore=50, FireConcrol_modelID=90010, Attack_Angle_Max=30, Attack_Angle_Min=30, Angular_Acceleration=0.2, Power_Efficiency=0.5, Speed_X=700, Round_Speed=0, Chassis_Creeping_Angle=60, Chassis_Creeping_Hight=85, Chassis_Correction=10, Attach= "0.0", engine_efficiency=0.015, },
	[10005] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=90010, Attack_Angle_Max=30, Attack_Angle_Min=30, Angular_Acceleration=0.2, Power_Efficiency=0.5, Speed_X=700, Round_Speed=0, Chassis_Creeping_Angle=60, Chassis_Creeping_Hight=85, Chassis_Correction=10, Attach= "0.0", engine_efficiency=0.015, },
	[10006] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10007] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10008] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=3000000, Charge_During=0.0, CD=0.4, Overheat=10.0, Effect_Life=5800.0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10009] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=0, Charge_During=0, CD=0, Overheat=0, Effect_Life=0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10010] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=0, Charge_During=0, CD=0, Overheat=0, Effect_Life=0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10011] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=0, Charge_During=0, CD=0, Overheat=0, Effect_Life=0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10012] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=0, Charge_During=0, CD=0, Overheat=0, Effect_Life=0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10013] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=0, Charge_During=0, CD=0, Overheat=0, Effect_Life=0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[10014] = {AI_Name= "", K1=0, K2=0, Blueprint= "", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=0, Charge_During=0, CD=0, Overheat=0, Effect_Life=0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
	[90001] = {AI_Name= "蓝翔毕业挖掘机", K1=0, K2=0, Blueprint= "BehaviorTree'/Game/Blueprints/Battle/NPC/AI/BT_Excavator.BT_Excavator'", Weapon_modelID=0, Weapon_Type=0, Damage_Type=0, Damage_Rad=0, Break_Rad=0, Break_Strength=0, Base_Damage=0, InitialSpeedMax=0, MaxSpeed=0, Charge_During=0, CD=0, Overheat=0, Effect_Life=0, Body_modelID=0, Hp=0, Hp_Restore=0, Sheld_Type=0, Sheld_Value=0, Shield_Damage_Reduce=0, Body_Damage=0, Sheld_Restore=0, Power_Value=0, Power_Restore=0, FireConcrol_modelID=0, Attack_Angle_Max=0, Attack_Angle_Min=0, Angular_Acceleration=0, Power_Efficiency=0, Speed_X=0, Round_Speed=0, Chassis_Creeping_Angle=0, Chassis_Creeping_Hight=0, Chassis_Correction=0, Attach= "", engine_efficiency=0, },
};return AI